"""Constants for the SSH integration."""

DOMAIN = "ssh"

DEFAULT_HOST_KEYS_FILENAME = "known_hosts"
DEFAULT_UPDATE_INTERVAL = 30

CONF_ACTION_COMMANDS = "action_commands"
CONF_ADD_HOST_KEYS = "add_host_keys"
CONF_ALLOW_TURN_OFF = "allow_turn_off"
CONF_COMMAND_SET = "command_set"
CONF_COMMAND_TIMEOUT = "command_timeout"
CONF_DEFAULT_COMMANDS = "default_commands"
CONF_DYNAMIC = "dynamic"
CONF_ENTITY_REGISTRY_ENABLED_DEFAULT = "entity_registry_enabled_default"
CONF_FLOAT = "float"
CONF_HOST_KEYS_FILENAME = "host_keys_filename"
CONF_KEY = "key"
CONF_KEY_FILENAME = "key_filename"
CONF_OPTIONS = "options"
CONF_PATTERN = "pattern"
CONF_SENSORS = "sensors"
CONF_SENSOR_COMMANDS = "sensor_commands"
CONF_SEPARATOR = "separator"
CONF_SUGGESTED_DISPLAY_PRECISION = "suggested_display_precision"
CONF_SUGGESTED_UNIT_OF_MEASUREMENT = "suggested_unit_of_measurement"
CONF_UPDATE_INTERVAL = "update_interval"

SERVICE_EXECUTE_COMMAND = "execute_command"
SERVICE_POLL_SENSOR = "poll_sensor"
SERVICE_RESTART = "restart"
SERVICE_RUN_ACTION = "run_action"
SERVICE_TURN_OFF = "turn_off"
SERVICE_TURN_ON = "turn_on"
