"""Constants for the SSH integration."""

DOMAIN = "ssh"

CONF_DEFAULT_COMMAND_SET = "default_command_set"
CONF_SSH_PORT = "ssh_port"
CONF_SSH_USER = "ssh_user"
CONF_SSH_PASSWORD = "ssh_password"
CONF_SSH_KEY_FILE = "ssh_key_file"
CONF_SSH_HOST_KEYS_FILE = "ssh_host_keys_file"
CONF_PING_TIMEOUT = "ping_timeout"
CONF_SSH_TIMEOUT = "ssh_timeout"
CONF_COMMAND_TIMEOUT = "command_timeout"
CONF_ACTION_COMMANDS = "action_commands"
CONF_SENSOR_COMMANDS = "sensor_commands"
CONF_KEY = "key"
CONF_SEPARATOR = "separator"
CONF_SENSORS = "sensors"
CONF_VALUE_TYPE = "value_type"
CONF_VALUE_MIN = "value_min"
CONF_VALUE_MAX = "value_max"
CONF_DYNAMIC = "dynamic"
CONF_SUGGESTED_UNIT_OF_MEASUREMENT = "suggested_unit_of_measurement"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_ADD_HOST_KEYS = "add_host_keys"
CONF_ALLOW_TURN_OFF = "allow_turn_off"
CONF_CONTEXT = "context"
CONF_COMMAND_SET = "command_set"

SERVICE_TURN_ON = "turn_on"
SERVICE_TURN_OFF = "turn_off"
SERVICE_EXECUTE_COMMAND = "execute_command"
SERVICE_RUN_ACTION = "run_action"
SERVICE_POLL_SENSOR = "poll_sensor"
